version: "3.7"
services:
  postgres:
    container_name: crypto-pg
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports: 
      - '5432:5432'
    volumes:
      - db-vol:/var/lib/postgresql/data

  redis:
    container_name: crypto_redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379

  scheduler:
    container_name: crypto-scheduler
    build:
      context: .
      dockerfile: ./docker/scheduler.dockerfile
    entrypoint: ["./scripts/wait-for-it.sh", "postgres:5432", "--", "npm",  "run", "scheduler"]
    restart: always
    depends_on:
      - postgres
    environment:
      - DSN=${PG_DSN}
      - WS_PORT=${WS_PORT}
    ports:
      - 4501:4501

  api:
    container_name: crypto-api
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    entrypoint: ["./scripts/wait-for-it.sh", "postgres:5432", "--", "npm",  "run", "server"]
    ports:
      - 4500:4500
    restart: always
    depends_on:
      - postgres
    environment:
      - API_PORT=${API_PORT}
      - DSN=${PG_DSN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - CACHE_TIME=${CACHE_TIME}

volumes:
  db-vol:
